server:
   port: 8090

spring:
   application:
      name: microservicios-zuul


eureka:
 client:  
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/


zuul:
  sensitiveHeaders:  Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    alquiler:
      path: /api/alquiler/**
      serviceId: microservicio-alquiler
      stripPrefix: true